### ISSUE TITLE
Can this plugin be installed via nmp?

### ISSUE THREAD

**Issue by zunjooo** [sitespeedio/plugin-gpsi#1]
Greeting,

so I cloned gpsi plugin inside my local folder and installed it with docker, but is there an option to install this plugin directly with npm?

**Comment by soulgalore** [comment]
I haven't pushed it to npm yet, you still need to clone it and then point it out as in https://www.sitespeed.io/documentation/sitespeed.io/plugins/#relative-using-nodejs

Best
Peter

**Comment by zunjooo** [comment]
Do you maybe have a plan to push it on npm? :)

btw thank you for a quick response!

**Comment by soulgalore** [comment]
Yes I can do it but need to think about the path etc so that everything is setup correctly. Can you help me with that?

**Comment by zunjooo** [comment]
I'm learning this stuff at the moment, but I will be happy to help you out. I' gonna keep an eye on this. :)

**Comment by soulgalore** [comment]
Lets follow the rest of the sitespeed.io projects and do a release bash file that fixes this.

**Comment by soulgalore** [comment]
This is pushed now to npm
