### ISSUE TITLE
Metrics from GPSI plugin seem to be outdated? DOM Content Loaded instead of First Input Delay

### ISSUE THREAD

**Issue by fxbtr** [sitespeedio/plugin-gpsi#17]
Hello,

I tried to use the Lighthouse and GPSI plugin thanks to the _plus1_ docker image in order to retrieve the CrUX data for First Contentful Paint and First Input Delay.

When I add the metrics.list parameter, I notice that the FCP is available and everything is working perfectly: `gpsi.pageSummary.loadingExperience.metrics.FIRST_CONTENTFUL_PAINT_MS.median`

The DCL is also available: `gpsi.pageSummary.loadingExperience.metrics.DOM_CONTENT_LOADED_EVENT_FIRED_MS.median`

But unless i'm mistaken not the FID. 

The FCP - DCL combo available makes me wonder if it isn't the version 4 of the PageSpeed Insights API being used instead of the 5 ? See this doc about the deprecated v4 mentionning FCP and DCL but not FID: https://developers.google.com/speed/docs/insights/faq

What I'm running
> docker run --rm -v C:\Git\Budgets-Batch:/sitespeed.io sitespeedio/sitespeed.io:9.8.1-plus1 --config ./config/mobile.json --budget.configPath ./budgets/FP/myBudget.json ./urls/FPbypass.txt --graphite.namespace sitespeed_io.smsFirstView_NoConsent --webpagetest.file ./scripts/WPT_NoConsent.txt --metrics.list

How can we retrieve the FID from GPSI?

Thank you for help
Best regards

**Comment by fxbtr** [comment]
Hi Peter, thanks for your answer.

I am looking into it a bit further and gpagespeed returns FCP and DCL, as per the return example given here: https://github.com/zrrrzzt/gpagespeed/blob/HEAD/return-example.md
Here is a return example for the latest pagespeed API (v5) with FCP and FID : https://gist.github.com/fxbtr/b1c2b429776f4967d3df620dec2439ad

Also, this paragraph mentions v4 as default for gpagespeed (instead of the current v5 pagespeed API): https://www.npmjs.com/package/gpagespeed#alternative-api

So I'm not sure either, maybe I can try to reach the creator

**Comment by soulgalore** [comment]
I think Google just kept the old one and then launched a new without changing the old :(

https://github.com/GoogleChromeLabs/psi gives the new thing, I'll make a task for updating to that.

**Comment by soulgalore** [comment]
I created a branch see https://github.com/sitespeedio/plugin-gpsi/issues/19 for that but I don't have time right now to fix the output (but we do get the right data).

**Comment by soulgalore** [comment]
I've merged the fix for using the new API in https://github.com/sitespeedio/plugin-gpsi/pull/20 - if you use the plugin standalone you can use it now. I'm releasing the container in a couple of days.

**Comment by fxbtr** [comment]
Looks like it's working great! thanks Peter
