### ISSUE TITLE
Using docker image - canonical way to install plugin?

### ISSUE THREAD

**Issue by kkopachev** [sitespeedio/plugin-gpsi#2]
I'm using sitespeed.io:6.0.3 image. Unpacked this plugin into local directory (plugin-gpsi) and running something like this:
```
docker run --privileged --shm-size=1g --rm \
 -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:6.0.3 \
 -c cable -b chrome \
 --plugins.add "/sitespeed.io/plugin-gpsi" \
 -n1 https://www.sitespeed.io/
```
But I'm unable to use the plugin, since it missing `gpagespeed` dependency:
```
Couldn't load plugin /sitespeed.io/plugin-gpsi: Error: Cannot find module '/usr/src/app/lib/plugins/sitespeed.io/plugin-gpsi'
[2017-12-06 00:33:23] ERROR: Error: Cannot find module 'gpagespeed'
......
```

Trying to avoid shipping my custom docker image, is there a good way to make that work using just local mount?

**Comment by soulgalore** [comment]
Hey @kkopachev check if this works for you:
https://www.sitespeed.io/documentation/sitespeed.io/plugins/#mount-your-plugin-in-docker

Best
Peter

**Comment by kkopachev** [comment]
Hi @soulgalore 

That's exactly what I did. But it does not work, because [gpagespeed](https://github.com/sitespeedio/plugin-gpsi/blob/master/package.json#L38) dependency is not installed in the container and could not be found.

**Comment by kkopachev** [comment]
So it works if I not only download plugin release and unpack it to mounted directory, but I also have to run npm install under plugin directory, so it fetches all required dependencies. 
Kind of a lot of work. I imagine node used to install plugin should match node version used in sitespeed.io, otherwise it could pull invalid dependencies. 
Could not figure out reliable way to put all this into a jenkins job without creating custom docker image which bundle sitespeed.io+plugin(s).

**Comment by soulgalore** [comment]
yep I know, but I don't know another way we could handle it? The reason of moving out GPSI is to have smaller codebase. The install method, I think Grafana has the same structure, but if you have any idea of how we can make it easier let us know.

And I think things like https://github.com/betit/chrometrace-sitespeedio-plugin would be more valuable to move in the project instead of keeping GPSI but that's IMHO.

Best
Peter

**Comment by kkopachev** [comment]
What if sitespeed.io would install plugins upon start up of a container? entrypoint would parse a list of plugins (npm package names) from cli, pre-install it and then run sitespeed.io normally, specifying freshly installed plugins?

**Comment by soulgalore** [comment]
I think the problem with installing on demand is that its hard to debug when the user has a lot of different plugins installed (from my side).
