### ISSUE TITLE
Google Page Speed Insights Failing with Error

### ISSUE THREAD

**Issue by dekryptic** [sitespeedio/plugin-gpsi#24]
Having trouble getting GPSI working. It doesn't show up in the html or as json.

```
ERROR: TypeError: Cannot read property 'FIRST_CONTENTFUL_PAINT_MS' of undefined at Object.repackage (/gpsi/lib/pageSummary.js:37:49) at /gpsi/lib/index.js:88
```

Docker command: `--plugins.add analysisstorer --gpsi.key ${GPSI_KEY} -n 1 --webpagetest.host http://localhost:4000 --webpagetest.location Test --video ${URL}`

Docker Image: `sitespeedio/sitespeed.io:12.6.0-plus1`

Strangely enough if I run it again I get no error but no GPSI data anywhere either.

**Comment by soulgalore** [comment]
Thank you @dekryptic it really helps with the failing URL! Its fixed in https://github.com/sitespeedio/plugin-gpsi/pull/23 and I will push that in the next release, hopefully tomorrow nigh.

**Comment by soulgalore** [comment]
This has been fixed.
