### ISSUE TITLE
Issues with only some sites (like ours) when trying to use GPSI with the 16.0.1-plus1 docker image

### ISSUE THREAD

**Issue by mginams** [sitespeedio/plugin-gpsi#35]
I've tried about 10 or so variations of this command, placing the --gpsi.key in various locations:

docker run --rm -v "$(pwd):/sitespeed.io" --network=root_default sitespeedio/sitespeed.io:16.0.1-plus1 --gpsi.key s00pers3kr1t --graphite.host=graphite https://measure.works/ -n 1

Including an explicit call to add the plugin with --plugins.add and adding my gpsi.key there as well but for our site https://measure.works/ I always get this error

[2020-12-29 09:54:19] ERROR: TypeError: Cannot read property 'metrics' of undefined
    at Object.repackage (/gpsi/lib/pageSummary.js:37:37)
    at /gpsi/lib/index.js:89:50
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

For most other sites Lighthouse and gpsi just work but I suspected that as we do a lot of inhumane testing on our own site that we might be getting null data back due to rate limiting.

This seems to have been confirmed by testing the API using curl, without my API key I get a "too many queries, resource exhausted" response and with the api key appended to the URL I get data. 

curl https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://measure.works/&key=xxyyzz  works fine.

As a final check I appended my API key to the URL in the command like so and got an interesting response back referencing some default google api project which matches the response I get with curl without my own api key.

docker run --rm -v "$(pwd):/sitespeed.io" --network=root_default sitespeedio/sitespeed.io:16.0.1-plus1 --graphite.host=graphite https://measure.works/?key=xxYYzz -n 1

returns the following. It seems like my own API key is not being properly fed in to the API. The project number referenced is some default you get when you don't use a project API key at all. 

[2020-12-29 10:21:36] INFO: Sending url https://measure.works/?key=xxyyzz to test on Page Speed Insights
[2020-12-29 10:21:36] ERROR: Error: Quota exceeded for quota group 'default' and limit 'Queries per 100 seconds' of service 'pagespeedonline.googleapis.com' for consumer 'project_number:583797351490'.
    at Gaxios.<anonymous> (/gpsi/node_modules/gaxios/build/src/gaxios.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (/gpsi/node_modules/gaxios/build/src/gaxios.js:16:58)

Just as curl https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=https://measure.works/ returns

    "code": 429,
    "message": "Quota exceeded for quota group 'default' and limit 'Queries per 100 seconds' of service 'pagespeedonline.googleapis.com' for consumer 'project_number:583797351490'.",
    "errors": [
      {
        "message": "Quota exceeded for quota group 'default' and limit 'Queries per 100 seconds' of service 'pagespeedonline.googleapis.com' for consumer 'project_number:583797351490'.",
        "domain": "global",
        "reason": "rateLimitExceeded"
      }
    ],
    "status": "RESOURCE_EXHAUSTED"

Hopefully I'm just not feeding the key in correctly but maybe this doesn't work with the docker-plus1 image. Happy to do any debug runs if needed though even with the -vvv switch I didn't catch anything about rate limits and quotas.

Thanks-Mike.

**Comment by mginams** [comment]
This works for me now, don't know if anything changed in the code or just the fact that I rebuilt the env on a different VM but I see the google API is now passed correctly (verified by the fact that when you exceed the 1 query per minute limit the full URL sent to googleapis is visible and that string works just fine from CURL once you're outta the penalty box) so I'll close this off.

**Comment by soulgalore** [comment]
There was a push that limited the number of simultaneously tests in https://github.com/sitespeedio/plugin-gpsi/pull/31  but it took some time until it reached the Docker container (if you use that).

**Comment by mginams** [comment]
Ah ha, yes I use the docker containers to check out newer releases. In the future I'll take possible latency with code pushes into account (or just try not to be so lazy).
