### ISSUE TITLE
YOUR_GPSI_KEY

### ISSUE THREAD

**Issue by taytus** [sitespeedio/plugin-gpsi#4]
Sorry for the dumb question but where/how do I get that key?
Thanks!

**Comment by soulgalore** [comment]
Hey @taytus there are no dumb question :) You need to register at Google to get the key, I don’t have.a direct link but try searching for it. If you find it, please let me know so I can update the README.
Best
Peter

**Comment by soulgalore** [comment]
https://support.google.com/cloud/answer/6158862

**Comment by taytus** [comment]
Got it! I think I made it work.
It's not giving me errors when I add the plugin. 
What should I see differently in the report? What's/where is the new section added.
I thought this will add a lot of values coming from GPSI but I can't find those. I'm new to sitespeed.io so maybe is there and I don't see it :P
Thank you!

**Comment by soulgalore** [comment]
There should be a new tab on the page summary page named GPSI?

**Comment by taytus** [comment]
Hello @soulgalore 

Sorry, something is not working... and I'm not sure what I'm doing wrong because no error message or warning is being displayed.

1. I cloned the repo and followed all the steps to add the plugin
2- When I ran sitespeed.io using bin/sitespeed.js --plugins.add ../plugin-gpsi/lib/ --gpsi.key MY_GPSI_KEY https://www.sitespeed.io/ -n 1, everything seems to be working. I have these output messaages:

> Sending url https://www.sitespeed.io/ to test on Page Speed Insights
and
> Got https://www.sitespeed.io/ analysed from Google Page Speed Insights

So I guess the plugin is working.

But no tab has been added to my report: https://www.dropbox.com/s/zq3pbgr6vrmagut/Screenshot%202018-06-21%2016.20.39.png?dl=0

Any idea what I'm doing wrong?

Any other info I could provide?

Thank you so much for your time.

**Comment by soulgalore** [comment]
Hey @taytus np I think you are just looking at the wrong place. Click on "Pages" and then choose one of the URLs that you have tested. Then you should have an extra tab here:
<img width="807" alt="screen shot 2018-06-22 at 7 58 21 am" src="https://user-images.githubusercontent.com/540757/41762250-155c411e-75f2-11e8-845b-1cde6a1e1309.png">

Best
Peter

**Comment by taytus** [comment]
Hi @soulgalore,

Thank you so much for your help Peter, I really appreciate it. Sadly, even when I've followed all the steps and tried different ways to install the plugin, I haven't been successful.

Please feel free to close this ticket.

Feature request: It would be awesome if we could have a 1-minute video (or less) showing how to install the plugin.

Cheers.

**Comment by soulgalore** [comment]
Great! Thanks @taytus . Yep good idea. Ping @beenanner what do you think about a video for how to run plugins? I like that idea.

Best
Peter

**Comment by beenanner** [comment]
Sound like a great idea!
